-- Group Trip Planner: first installation only.
-- Generated by node scripts/build-install-sql.mjs; do not edit this copy.
-- Run this WHOLE file ONCE in the correct Supabase SQL Editor.
-- Contains migrations 202610040001_private_groups.sql, 202610040002_collaboration.sql, 202610040003_profiles_group_names.sql.
-- No private trip data is included. Existing app installations must use migrations instead.
begin;
do $$
begin
  if exists (select 1 from pg_catalog.pg_namespace where nspname = 'app_private')
     or exists (select 1 from pg_catalog.pg_tables where schemaname = 'public' and tablename in ('groups', 'group_members', 'trips', 'trip_participants', 'trip_stops', 'activities', 'lodgings', 'transfers', 'group_invitations', 'activity_preferences', 'activity_comments', 'itinerary_days', 'itinerary_items', 'plan_approvals', 'profiles')) then
    raise exception 'Existing Group Trip Planner schema detected. Stop and inspect before applying migrations. No changes applied.';
  end if;
end $$;

-- Source: 202610040001_private_groups.sql
-- Private groups and explicitly selected, independent starter trips.
-- Supabase provides auth.users, auth.uid(), anon and authenticated.

create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;
grant usage on schema app_private to authenticated;

create table public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(btrim(name)) between 1 and 120),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
create table public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','member')),
  joined_at timestamptz not null default now(),
  primary key (group_id,user_id)
);
create unique index group_single_owner on public.group_members(group_id) where role = 'owner';
create index group_members_by_user on public.group_members(user_id,group_id);
create table public.trips (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  name text not null check (length(btrim(name)) between 1 and 120),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  timezone text not null default 'UTC' check (length(timezone) between 1 and 100),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object' and octet_length(details::text) <= 524288),
  created_by uuid not null references auth.users(id),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now()
);
create index trips_by_group on public.trips(group_id);
create table public.trip_participants (
  trip_id uuid not null references public.trips(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null check (status in ('going','undecided','not_going')),
  updated_at timestamptz not null default now(),
  primary key (trip_id,user_id)
);
create table public.trip_stops (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  name text not null check (length(btrim(name)) between 1 and 120),
  position integer not null default 0 check (position between 0 and 10000),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  unique (trip_id,id)
);
create table public.activities (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  stop_id uuid,
  title text not null check (length(btrim(title)) between 1 and 200),
  description text not null default '' check (length(description) <= 20000),
  why_visit text not null default '' check (length(why_visit) <= 10000),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object' and octet_length(details::text) <= 102400),
  created_by uuid not null default auth.uid() references auth.users(id),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  foreign key (trip_id,stop_id) references public.trip_stops(trip_id,id)
);
create table public.lodgings (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  stop_id uuid,
  title text not null check (length(btrim(title)) between 1 and 200),
  description text not null default '' check (length(description) <= 20000),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object' and octet_length(details::text) <= 102400),
  created_by uuid not null default auth.uid() references auth.users(id),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  foreign key (trip_id,stop_id) references public.trip_stops(trip_id,id)
);
create table public.transfers (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  stop_id uuid,
  title text not null check (length(btrim(title)) between 1 and 200),
  description text not null default '' check (length(description) <= 20000),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object' and octet_length(details::text) <= 102400),
  created_by uuid not null default auth.uid() references auth.users(id),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  foreign key (trip_id,stop_id) references public.trip_stops(trip_id,id)
);
create index activities_by_trip on public.activities(trip_id);
create index lodgings_by_trip on public.lodgings(trip_id);
create index transfers_by_trip on public.transfers(trip_id);
create table public.group_invitations (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  token_hash text not null unique,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  revoked_at timestamptz,
  accepted_at timestamptz,
  accepted_by uuid references auth.users(id),
  check ((accepted_at is null) = (accepted_by is null))
);
create index invitations_by_group on public.group_invitations(group_id);
create table app_private.operations (
  user_id uuid not null references auth.users(id) on delete cascade,
  operation text not null,
  request_id uuid not null,
  arguments jsonb not null,
  result_id uuid not null,
  primary key (user_id,operation,request_id)
);

create function app_private.member_role(p_group_id uuid) returns text
language sql stable security definer set search_path = '' as $$
  select m.role from public.group_members m where m.group_id = p_group_id and m.user_id = auth.uid()
$$;
create function app_private.is_member(p_group_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.group_members m where m.group_id = p_group_id and m.user_id = auth.uid())
$$;
create function app_private.is_editor(p_group_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.group_members m where m.group_id = p_group_id and m.user_id = auth.uid() and m.role in ('owner','admin'))
$$;
create function app_private.trip_member(p_trip_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.trips t join public.group_members m on m.group_id=t.group_id where t.id=p_trip_id and m.user_id=auth.uid())
$$;
create function app_private.trip_editor(p_trip_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.trips t join public.group_members m on m.group_id=t.group_id where t.id=p_trip_id and m.user_id=auth.uid() and m.role in ('owner','admin'))
$$;

alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.trips enable row level security;
alter table public.trip_participants enable row level security;
alter table public.trip_stops enable row level security;
alter table public.activities enable row level security;
alter table public.lodgings enable row level security;
alter table public.transfers enable row level security;
alter table public.group_invitations enable row level security;
create policy groups_read on public.groups for select to authenticated using (app_private.is_member(id));
create policy groups_edit on public.groups for update to authenticated using (app_private.is_editor(id)) with check (app_private.is_editor(id));
create policy members_read on public.group_members for select to authenticated using (app_private.is_member(group_id));
create policy trips_read on public.trips for select to authenticated using (app_private.is_member(group_id));
create policy trips_edit on public.trips for update to authenticated using (app_private.is_editor(group_id)) with check (app_private.is_editor(group_id));
create policy participants_read on public.trip_participants for select to authenticated using (app_private.trip_member(trip_id));
create policy stops_read on public.trip_stops for select to authenticated using (app_private.trip_member(trip_id));
create policy stops_insert on public.trip_stops for insert to authenticated with check (app_private.trip_editor(trip_id));
create policy stops_update on public.trip_stops for update to authenticated using (app_private.trip_editor(trip_id)) with check (app_private.trip_editor(trip_id));
create policy stops_delete on public.trip_stops for delete to authenticated using (app_private.trip_editor(trip_id));
create policy activities_read on public.activities for select to authenticated using (app_private.trip_member(trip_id));
create policy activities_insert on public.activities for insert to authenticated with check (app_private.trip_member(trip_id) and created_by=auth.uid());
create policy activities_update on public.activities for update to authenticated using (app_private.trip_member(trip_id) and (created_by=auth.uid() or app_private.trip_editor(trip_id))) with check (app_private.trip_member(trip_id) and (created_by=auth.uid() or app_private.trip_editor(trip_id)));
create policy activities_delete on public.activities for delete to authenticated using (app_private.trip_member(trip_id) and (created_by=auth.uid() or app_private.trip_editor(trip_id)));
create policy lodgings_read on public.lodgings for select to authenticated using (app_private.trip_member(trip_id));
create policy lodgings_insert on public.lodgings for insert to authenticated with check (app_private.trip_editor(trip_id) and created_by=auth.uid());
create policy lodgings_update on public.lodgings for update to authenticated using (app_private.trip_editor(trip_id)) with check (app_private.trip_editor(trip_id));
create policy lodgings_delete on public.lodgings for delete to authenticated using (app_private.trip_editor(trip_id));
create policy transfers_read on public.transfers for select to authenticated using (app_private.trip_member(trip_id));
create policy transfers_insert on public.transfers for insert to authenticated with check (app_private.trip_editor(trip_id) and created_by=auth.uid());
create policy transfers_update on public.transfers for update to authenticated using (app_private.trip_editor(trip_id)) with check (app_private.trip_editor(trip_id));
create policy transfers_delete on public.transfers for delete to authenticated using (app_private.trip_editor(trip_id));
create policy invitations_read on public.group_invitations for select to authenticated using (app_private.is_editor(group_id));

-- Supabase can grant broad default privileges: reset all before narrow grants.
revoke all on public.groups, public.group_members, public.trips, public.trip_participants, public.trip_stops, public.activities, public.lodgings, public.transfers, public.group_invitations from public, anon, authenticated;
grant select on public.groups, public.group_members, public.trips, public.trip_participants, public.trip_stops, public.activities, public.lodgings, public.transfers to authenticated;
grant update(name) on public.groups to authenticated;
grant update(name,currency,timezone,details) on public.trips to authenticated;
grant insert(trip_id,name,position), update(name,position), delete on public.trip_stops to authenticated;
grant insert(trip_id,stop_id,title,description,why_visit,details), update(stop_id,title,description,why_visit,details), delete on public.activities to authenticated;
grant insert(trip_id,stop_id,title,description,details), update(stop_id,title,description,details), delete on public.lodgings, public.transfers to authenticated;
grant select(id,group_id,created_by,created_at,expires_at,revoked_at,accepted_at,accepted_by) on public.group_invitations to authenticated;

create function app_private.bump_version() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.version := old.version + 1;
  return new;
end $$;
create function app_private.validate_timezone() returns trigger
language plpgsql set search_path = '' as $$
begin
  if not exists(select 1 from pg_catalog.pg_timezone_names where name = new.timezone) then
    raise exception 'Invalid timezone' using errcode='22023';
  end if;
  return new;
end $$;
create function app_private.touch_trip() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    update public.trips set version=version+1 where id=old.trip_id;
    return old;
  end if;
  update public.trips set version=version+1 where id=new.trip_id;
  return new;
end $$;
create trigger trips_version before update on public.trips for each row execute function app_private.bump_version();
create trigger trips_timezone before insert or update of timezone on public.trips for each row execute function app_private.validate_timezone();
create trigger stops_version before update on public.trip_stops for each row execute function app_private.bump_version();
create trigger activities_version before update on public.activities for each row execute function app_private.bump_version();
create trigger lodgings_version before update on public.lodgings for each row execute function app_private.bump_version();
create trigger transfers_version before update on public.transfers for each row execute function app_private.bump_version();
create trigger stops_touch after insert or update or delete on public.trip_stops for each row execute function app_private.touch_trip();
create trigger activities_touch after insert or update or delete on public.activities for each row execute function app_private.touch_trip();
create trigger lodgings_touch after insert or update or delete on public.lodgings for each row execute function app_private.touch_trip();
create trigger transfers_touch after insert or update or delete on public.transfers for each row execute function app_private.touch_trip();
create trigger participants_touch after insert or update or delete on public.trip_participants for each row execute function app_private.touch_trip();

create function app_private.require_user() returns uuid
language plpgsql stable set search_path = '' as $$
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  return auth.uid();
end $$;
create function app_private.lock_member(p_group_id uuid,p_editor boolean default false) returns void
language plpgsql set search_path = '' as $$
declare v_role text;
begin
  perform app_private.require_user();
  select role into v_role from public.group_members where group_id=p_group_id and user_id=auth.uid() for key share;
  if v_role is null or (p_editor and v_role not in ('owner','admin')) then raise exception 'Not authorized' using errcode='42501'; end if;
end $$;
create function app_private.operation_result(p_operation text,p_request_id uuid,p_arguments jsonb) returns uuid
language plpgsql set search_path = '' as $$
declare v_existing app_private.operations;
begin
  perform app_private.require_user();
  if p_request_id is null then raise exception 'Request ID required' using errcode='22023'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(auth.uid()::text || p_operation || p_request_id::text,0));
  select * into v_existing from app_private.operations where user_id=auth.uid() and operation=p_operation and request_id=p_request_id;
  if found then
    if v_existing.arguments is distinct from p_arguments then raise exception 'Request ID reused with different arguments' using errcode='22023'; end if;
    return v_existing.result_id;
  end if;
  return null;
end $$;
create function app_private.save_operation(p_operation text,p_request_id uuid,p_arguments jsonb,p_result_id uuid) returns void
language sql set search_path = '' as $$
  insert into app_private.operations(user_id,operation,request_id,arguments,result_id) values(auth.uid(),p_operation,p_request_id,p_arguments,p_result_id)
$$;

create function public.create_group(p_name text,p_request_id uuid) returns uuid
language plpgsql security definer set search_path = '' as $$
declare v_id uuid; v_args jsonb := jsonb_build_object('name',p_name);
begin
  v_id := app_private.operation_result('create_group',p_request_id,v_args);
  if v_id is not null then
    if not app_private.is_member(v_id) then raise exception 'Not authorized' using errcode='42501'; end if;
    return v_id;
  end if;
  insert into public.groups(name,created_by) values(btrim(p_name),auth.uid()) returning id into v_id;
  insert into public.group_members(group_id,user_id,role) values(v_id,auth.uid(),'owner');
  perform app_private.save_operation('create_group',p_request_id,v_args,v_id);
  return v_id;
end $$;
create function public.create_trip(p_group_id uuid,p_name text,p_template text,p_request_id uuid) returns uuid
language plpgsql security definer set search_path = '' as $$
declare v_id uuid; v_args jsonb := jsonb_build_object('group_id',p_group_id,'name',p_name,'template',p_template);
begin
  perform app_private.require_user();
  perform app_private.lock_member(p_group_id,true);
  if p_template is null or p_template not in ('blank','china') then raise exception 'Invalid template' using errcode='22023'; end if;
  v_id := app_private.operation_result('create_trip',p_request_id,v_args);
  if v_id is not null then return v_id; end if;
  insert into public.trips(group_id,name,created_by) values(p_group_id,btrim(p_name),auth.uid()) returning id into v_id;
  insert into public.trip_participants(trip_id,user_id,status) values(v_id,auth.uid(),'going');
  if p_template='china' then
    insert into public.trip_stops(trip_id,name,position) values(v_id,'Σαγκάη',0),(v_id,'Πεκίνο',1);
  end if;
  perform app_private.save_operation('create_trip',p_request_id,v_args,v_id);
  return v_id;
end $$;
create function public.create_invitation(p_group_id uuid) returns text
language plpgsql security definer set search_path = '' as $$
declare v_token text;
begin
  perform app_private.require_user();
  perform app_private.lock_member(p_group_id,true);
  v_token := replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','');
  insert into public.group_invitations(group_id,token_hash,created_by) values(p_group_id,encode(sha256(convert_to(v_token,'UTF8')),'hex'),auth.uid());
  return v_token;
end $$;
create function public.accept_invitation(p_token text) returns uuid
language plpgsql security definer set search_path = '' as $$
declare v_inv public.group_invitations;
begin
  perform app_private.require_user();
  if p_token is null or p_token !~ '^[0-9a-f]{64}$' then raise exception 'Invitation unavailable' using errcode='22023'; end if;
  select * into v_inv from public.group_invitations where token_hash=encode(sha256(convert_to(p_token,'UTF8')),'hex') for update;
  if not found or v_inv.revoked_at is not null or v_inv.accepted_at is not null or v_inv.expires_at <= now() then raise exception 'Invitation unavailable' using errcode='22023'; end if;
  if app_private.is_member(v_inv.group_id) then raise exception 'Already a member' using errcode='22023'; end if;
  insert into public.group_members(group_id,user_id,role) values(v_inv.group_id,auth.uid(),'member');
  update public.group_invitations set accepted_at=now(),accepted_by=auth.uid() where id=v_inv.id;
  return v_inv.group_id;
end $$;
create function public.revoke_invitation(p_invitation_id uuid) returns void
language plpgsql security definer set search_path = '' as $$
declare v_group uuid;
begin
  perform app_private.require_user();
  select group_id into v_group from public.group_invitations where id=p_invitation_id;
  if v_group is null or not app_private.is_editor(v_group) then raise exception 'Not authorized' using errcode='42501'; end if;
  update public.group_invitations set revoked_at=coalesce(revoked_at,now()) where id=p_invitation_id;
end $$;
create function public.remove_member(p_group_id uuid,p_user_id uuid) returns void
language plpgsql security definer set search_path = '' as $$
declare v_role text; v_target_role text;
begin
  perform app_private.require_user();
  v_role := app_private.member_role(p_group_id);
  select role into v_target_role from public.group_members where group_id=p_group_id and user_id=p_user_id for update;
  if v_role is null or v_role not in ('owner','admin') or v_target_role is null or v_target_role='owner' or (v_role='admin' and v_target_role='admin') then raise exception 'Not authorized' using errcode='42501'; end if;
  delete from public.trip_participants p using public.trips t where p.trip_id=t.id and t.group_id=p_group_id and p.user_id=p_user_id;
  delete from public.group_members where group_id=p_group_id and user_id=p_user_id;
end $$;
create function public.set_participation(p_trip_id uuid,p_status text) returns void
language plpgsql security definer set search_path = '' as $$
declare v_group uuid;
begin
  perform app_private.require_user();
  select group_id into v_group from public.trips where id=p_trip_id;
  perform app_private.lock_member(v_group,false);
  if p_status is null or p_status not in ('going','undecided','not_going') then raise exception 'Invalid status' using errcode='22023'; end if;
  insert into public.trip_participants(trip_id,user_id,status) values(p_trip_id,auth.uid(),p_status)
  on conflict (trip_id,user_id) do update set status=excluded.status,updated_at=now();
end $$;

create function public.reorder_stops(p_trip_id uuid,p_stop_ids uuid[],p_expected_version integer) returns integer
language plpgsql security definer set search_path = '' as $$
declare v_version integer; v_count integer;
begin
  perform app_private.require_user();
  if not app_private.trip_editor(p_trip_id) then raise exception 'Not authorized' using errcode='42501'; end if;
  select version into v_version from public.trips where id=p_trip_id for update;
  if p_expected_version is null or v_version is distinct from p_expected_version then raise exception 'Trip changed; refresh before reordering' using errcode='40001'; end if;
  select count(*) into v_count from public.trip_stops where trip_id=p_trip_id;
  if p_stop_ids is null or cardinality(p_stop_ids)<>v_count
    or (select count(distinct x) from unnest(p_stop_ids) x)<>v_count
    or exists(select 1 from unnest(p_stop_ids) x where not exists(select 1 from public.trip_stops s where s.id=x and s.trip_id=p_trip_id))
  then raise exception 'Invalid stop order' using errcode='22023'; end if;
  update public.trip_stops s set position=u.ordinality-1 from unnest(p_stop_ids) with ordinality as u(id,ordinality)
  where s.id=u.id and s.trip_id=p_trip_id and s.position is distinct from u.ordinality-1;
  select version into v_version from public.trips where id=p_trip_id;
  return v_version;
end $$;

create function app_private.allowed_keys(p_object jsonb,p_allowed text[]) returns void
language plpgsql immutable set search_path = '' as $$
begin
  if jsonb_typeof(p_object) is distinct from 'object' then raise exception 'Expected an object' using errcode='22023'; end if;
  if exists(select 1 from jsonb_object_keys(p_object) k where not(k=any(p_allowed))) then raise exception 'Unexpected import field' using errcode='22023'; end if;
end $$;
create function app_private.import_text(p_object jsonb,p_key text,p_max integer,p_required boolean default false) returns text
language plpgsql immutable set search_path = '' as $$
declare v_text text;
begin
  if not(p_object ? p_key) then
    if p_required then raise exception 'Required import field missing' using errcode='22023'; end if;
    return null;
  end if;
  if jsonb_typeof(p_object->p_key) is distinct from 'string' then raise exception 'Invalid import text' using errcode='22023'; end if;
  v_text := p_object->>p_key;
  if length(v_text)>p_max or (p_required and length(btrim(v_text))=0) then raise exception 'Invalid import text length' using errcode='22023'; end if;
  return v_text;
end $$;
create function public.import_private_trip(p_group_id uuid,p_payload jsonb,p_request_id uuid) returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  v_id uuid; v_stop_id uuid; v_args jsonb; v_item jsonb; v_trip jsonb; v_name text; v_key text;
  v_currency text; v_timezone text; v_title text; v_description text; v_why text; v_details jsonb; v_trip_details jsonb;
  v_stop_map jsonb := '{}'::jsonb; v_position integer := 0; v_kind text;
begin
  perform app_private.require_user();
  if not app_private.is_editor(p_group_id) then raise exception 'Not authorized' using errcode='42501'; end if;
  perform app_private.lock_member(p_group_id,true);
  if p_payload is null or octet_length(p_payload::text)>2097152 then raise exception 'Import too large or absent' using errcode='22023'; end if;
  perform app_private.allowed_keys(p_payload,array['schema_version','kind','trip','stops','activities','lodgings','transfers']);
  if not(p_payload ?& array['schema_version','kind','trip','stops','activities','lodgings','transfers']) or p_payload->'schema_version' is distinct from '1'::jsonb or p_payload->'kind' is distinct from '"private-trip"'::jsonb then raise exception 'Unsupported import format' using errcode='22023'; end if;
  v_trip := p_payload->'trip';
  perform app_private.allowed_keys(v_trip,array['name','currency','timezone','details']);
  v_name := app_private.import_text(v_trip,'name',120,true);
  v_currency := coalesce(app_private.import_text(v_trip,'currency',3),'EUR');
  v_timezone := coalesce(app_private.import_text(v_trip,'timezone',100),'UTC');
  v_trip_details := coalesce(v_trip->'details','{}'::jsonb);
  if jsonb_typeof(v_trip_details) is distinct from 'object' or octet_length(v_trip_details::text)>524288 then raise exception 'Invalid trip details object' using errcode='22023'; end if;
  if v_currency !~ '^[A-Z]{3}$' then raise exception 'Invalid currency' using errcode='22023'; end if;
  foreach v_kind in array array['stops','activities','lodgings','transfers'] loop
    if jsonb_typeof(p_payload->v_kind) is distinct from 'array' then raise exception 'Expected import array' using errcode='22023'; end if;
    if jsonb_array_length(p_payload->v_kind) > (case v_kind when 'stops' then 100 when 'activities' then 1000 else 200 end) then raise exception 'Too many import records' using errcode='22023'; end if;
  end loop;
  v_args := jsonb_build_object('group_id',p_group_id,'payload',p_payload);
  v_id := app_private.operation_result('import_private_trip',p_request_id,v_args);
  if v_id is not null then return v_id; end if;
  insert into public.trips(group_id,name,currency,timezone,details,created_by) values(p_group_id,btrim(v_name),v_currency,v_timezone,v_trip_details,auth.uid()) returning id into v_id;
  insert into public.trip_participants(trip_id,user_id,status) values(v_id,auth.uid(),'going');
  for v_item in select value from jsonb_array_elements(p_payload->'stops') loop
    perform app_private.allowed_keys(v_item,array['key','name']);
    v_key := app_private.import_text(v_item,'key',100,true);
    v_name := app_private.import_text(v_item,'name',120,true);
    if v_stop_map ? v_key then raise exception 'Duplicate stop key' using errcode='22023'; end if;
    insert into public.trip_stops(trip_id,name,position) values(v_id,btrim(v_name),v_position) returning id into v_stop_id;
    v_stop_map := v_stop_map || jsonb_build_object(v_key,v_stop_id::text);
    v_position := v_position+1;
  end loop;
  foreach v_kind in array array['activities','lodgings','transfers'] loop
    for v_item in select value from jsonb_array_elements(p_payload->v_kind) loop
      perform app_private.allowed_keys(v_item,case when v_kind='activities' then array['title','stop_key','description','why_visit','details'] else array['title','stop_key','description','details'] end);
      v_title := app_private.import_text(v_item,'title',200,true);
      v_description := coalesce(app_private.import_text(v_item,'description',20000),'');
      v_why := coalesce(app_private.import_text(v_item,'why_visit',10000),'');
      v_details := coalesce(v_item->'details','{}'::jsonb);
      if jsonb_typeof(v_details) is distinct from 'object' or octet_length(v_details::text)>102400 then raise exception 'Invalid details object' using errcode='22023'; end if;
      v_stop_id := null;
      if v_item ? 'stop_key' and v_item->'stop_key' <> 'null'::jsonb then
        v_key := app_private.import_text(v_item,'stop_key',100,true);
        if not(v_stop_map ? v_key) then raise exception 'Unknown stop reference' using errcode='22023'; end if;
        v_stop_id := (v_stop_map->>v_key)::uuid;
      end if;
      if v_kind='activities' then
        insert into public.activities(trip_id,stop_id,title,description,why_visit,details,created_by) values(v_id,v_stop_id,btrim(v_title),v_description,v_why,v_details,auth.uid());
      elsif v_kind='lodgings' then
        insert into public.lodgings(trip_id,stop_id,title,description,details,created_by) values(v_id,v_stop_id,btrim(v_title),v_description,v_details,auth.uid());
      else
        insert into public.transfers(trip_id,stop_id,title,description,details,created_by) values(v_id,v_stop_id,btrim(v_title),v_description,v_details,auth.uid());
      end if;
    end loop;
  end loop;
  perform app_private.save_operation('import_private_trip',p_request_id,v_args,v_id);
  return v_id;
end $$;

create function public.create_stop(p_trip_id uuid,p_name text,p_position integer,p_request_id uuid) returns uuid
language plpgsql security definer set search_path = '' as $$
declare v_group uuid; v_id uuid; v_args jsonb := jsonb_build_object('trip_id',p_trip_id,'name',p_name,'position',p_position);
begin
  perform app_private.require_user();
  select group_id into v_group from public.trips where id=p_trip_id;
  perform app_private.lock_member(v_group,true);
  v_id := app_private.operation_result('create_stop',p_request_id,v_args);
  if v_id is not null then return v_id; end if;
  insert into public.trip_stops(trip_id,name,position) values(p_trip_id,btrim(p_name),p_position) returning id into v_id;
  perform app_private.save_operation('create_stop',p_request_id,v_args,v_id);
  return v_id;
end $$;

create function public.create_item(p_table text,p_trip_id uuid,p_fields jsonb,p_request_id uuid) returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  v_group uuid; v_id uuid; v_args jsonb; v_stop_id uuid;
  v_title text; v_description text; v_why text; v_details jsonb;
begin
  perform app_private.require_user();
  if p_table is null or p_table not in ('activities','lodgings','transfers') then raise exception 'Invalid item table' using errcode='22023'; end if;
  select group_id into v_group from public.trips where id=p_trip_id;
  perform app_private.lock_member(v_group,p_table<>'activities');
  perform app_private.allowed_keys(p_fields,case when p_table='activities' then array['title','description','why_visit','stop_id','details'] else array['title','description','stop_id','details'] end);
  v_title := app_private.import_text(p_fields,'title',200,true);
  v_description := coalesce(app_private.import_text(p_fields,'description',20000),'');
  v_why := coalesce(app_private.import_text(p_fields,'why_visit',10000),'');
  v_details := coalesce(p_fields->'details','{}'::jsonb);
  if jsonb_typeof(v_details) is distinct from 'object' or octet_length(v_details::text)>102400 then raise exception 'Invalid details object' using errcode='22023'; end if;
  if p_fields ? 'stop_id' and p_fields->'stop_id' <> 'null'::jsonb then
    v_stop_id := app_private.import_text(p_fields,'stop_id',36,true)::uuid;
  end if;
  v_args := jsonb_build_object('table',p_table,'trip_id',p_trip_id,'fields',p_fields);
  v_id := app_private.operation_result('create_item',p_request_id,v_args);
  if v_id is not null then return v_id; end if;
  if p_table='activities' then
    insert into public.activities(trip_id,stop_id,title,description,why_visit,details,created_by) values(p_trip_id,v_stop_id,btrim(v_title),v_description,v_why,v_details,auth.uid()) returning id into v_id;
  elsif p_table='lodgings' then
    insert into public.lodgings(trip_id,stop_id,title,description,details,created_by) values(p_trip_id,v_stop_id,btrim(v_title),v_description,v_details,auth.uid()) returning id into v_id;
  else
    insert into public.transfers(trip_id,stop_id,title,description,details,created_by) values(p_trip_id,v_stop_id,btrim(v_title),v_description,v_details,auth.uid()) returning id into v_id;
  end if;
  perform app_private.save_operation('create_item',p_request_id,v_args,v_id);
  return v_id;
end $$;

revoke all on all tables in schema app_private from public, anon, authenticated;
revoke all on all functions in schema app_private from public, anon, authenticated;
grant execute on function app_private.is_member(uuid), app_private.is_editor(uuid), app_private.trip_member(uuid), app_private.trip_editor(uuid) to authenticated;
revoke all on function public.create_group(text,uuid), public.create_trip(uuid,text,text,uuid), public.create_stop(uuid,text,integer,uuid), public.create_item(text,uuid,jsonb,uuid), public.create_invitation(uuid), public.accept_invitation(text), public.revoke_invitation(uuid), public.remove_member(uuid,uuid), public.set_participation(uuid,text), public.reorder_stops(uuid,uuid[],integer), public.import_private_trip(uuid,jsonb,uuid) from public, anon, authenticated;
grant execute on function public.create_group(text,uuid), public.create_trip(uuid,text,text,uuid), public.create_stop(uuid,text,integer,uuid), public.create_item(text,uuid,jsonb,uuid), public.create_invitation(uuid), public.accept_invitation(text), public.revoke_invitation(uuid), public.remove_member(uuid,uuid), public.set_participation(uuid,text), public.reorder_stops(uuid,uuid[],integer), public.import_private_trip(uuid,jsonb,uuid) to authenticated;

-- Source: 202610040002_collaboration.sql
-- Collaborative preferences, comments and a separately edited official plan.
-- Requires 202610040001_private_groups.sql. No private seed data.

alter table public.trips add column start_date date
  check (start_date between date '0001-01-01' and date '9999-12-31');
alter table public.group_members add column display_name text not null default ''
  check (length(display_name) <= 80);
alter table public.activities add constraint activities_trip_id_id_unique unique (trip_id,id);

create table public.activity_preferences (
  trip_id uuid not null references public.trips(id) on delete cascade,
  activity_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  choice text not null check (choice in ('must','yes','maybe','skip')),
  priority integer not null default 0 check (priority between 0 and 5),
  note text not null default '' check (length(note) <= 1000),
  updated_at timestamptz not null default now(),
  primary key(activity_id,user_id),
  foreign key(trip_id,activity_id) references public.activities(trip_id,id) on delete cascade
);
create index preferences_by_trip on public.activity_preferences(trip_id);
create table public.activity_comments (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  activity_id uuid not null,
  created_by uuid not null references auth.users(id),
  body text not null check (length(btrim(body)) between 1 and 3000),
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key(trip_id,activity_id) references public.activities(trip_id,id) on delete cascade
);
create index comments_by_trip_activity on public.activity_comments(trip_id,activity_id,created_at);
create table public.itinerary_days (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  day_number integer not null check(day_number between 1 and 365),
  title text not null default '' check(length(title) <= 120),
  stop_id uuid,
  notes text not null default '' check(length(notes) <= 3000),
  unique(trip_id,id),
  unique(trip_id,day_number),
  foreign key(trip_id,stop_id) references public.trip_stops(trip_id,id)
);
create table public.itinerary_items (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  day_id uuid not null,
  activity_id uuid,
  title text not null check(length(btrim(title)) between 1 and 200),
  position integer not null default 0 check(position between 0 and 10000),
  time_slot text check(time_slot ~ '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'),
  duration_minutes integer check(duration_minutes between 0 and 1440),
  notes text not null default '' check(length(notes) <= 3000),
  is_alternative boolean not null default false,
  subgroup text not null default '' check(length(subgroup) <= 120),
  foreign key(trip_id,day_id) references public.itinerary_days(trip_id,id),
  foreign key(trip_id,activity_id) references public.activities(trip_id,id)
);
create index itinerary_items_by_day on public.itinerary_items(trip_id,day_id,position);
create table public.plan_approvals (
  trip_id uuid not null references public.trips(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  version integer not null check(version > 0),
  approved_at timestamptz not null default now(),
  primary key(trip_id,user_id)
);

alter table public.activity_preferences enable row level security;
alter table public.activity_comments enable row level security;
alter table public.itinerary_days enable row level security;
alter table public.itinerary_items enable row level security;
alter table public.plan_approvals enable row level security;
create policy preferences_read on public.activity_preferences for select to authenticated using(app_private.trip_member(trip_id));
create policy comments_read on public.activity_comments for select to authenticated using(app_private.trip_member(trip_id));
create policy itinerary_days_read on public.itinerary_days for select to authenticated using(app_private.trip_member(trip_id));
create policy itinerary_items_read on public.itinerary_items for select to authenticated using(app_private.trip_member(trip_id));
create policy plan_approvals_read on public.plan_approvals for select to authenticated using(app_private.trip_member(trip_id));
revoke all on public.activity_preferences, public.activity_comments, public.itinerary_days, public.itinerary_items, public.plan_approvals from public,anon,authenticated;
grant select on public.activity_preferences, public.activity_comments, public.itinerary_days, public.itinerary_items, public.plan_approvals to authenticated;
-- Existing member SELECT privilege intentionally includes the new display_name.
-- No direct start_date/display_name writes are granted: the RPCs control them.

create trigger itinerary_days_touch after insert or update or delete on public.itinerary_days for each row execute function app_private.touch_trip();
create trigger itinerary_items_touch after insert or update or delete on public.itinerary_items for each row execute function app_private.touch_trip();
create trigger comments_version before update on public.activity_comments for each row execute function app_private.bump_version();

create function app_private.clear_removed_member_choices() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  delete from public.activity_preferences p using public.trips t where p.trip_id=t.id and t.group_id=old.group_id and p.user_id=old.user_id;
  delete from public.plan_approvals a using public.trips t where a.trip_id=t.id and t.group_id=old.group_id and a.user_id=old.user_id;
  return old;
end $$;
create trigger removed_member_choices before delete on public.group_members for each row execute function app_private.clear_removed_member_choices();

create function app_private.lock_plan(p_trip_id uuid,p_editor boolean default true) returns integer
language plpgsql set search_path = '' as $$
declare v_group uuid; v_version integer;
begin
  select group_id into v_group from public.trips where id=p_trip_id;
  perform app_private.lock_member(v_group,p_editor);
  select version into v_version from public.trips where id=p_trip_id for update;
  if not found then raise exception 'Not authorized' using errcode='42501'; end if;
  return v_version;
end $$;
create function app_private.check_plan_version(p_actual integer,p_expected integer) returns void
language plpgsql immutable set search_path = '' as $$
begin
  if p_expected is null or p_actual is distinct from p_expected then
    raise exception 'Plan changed; refresh before saving' using errcode='40001';
  end if;
end $$;
create function app_private.json_integer(p_object jsonb,p_key text,p_min integer,p_max integer,p_nullable boolean default false) returns integer
language plpgsql immutable set search_path = '' as $$
declare v_value numeric;
begin
  if p_nullable and p_object->p_key = 'null'::jsonb then return null; end if;
  if jsonb_typeof(p_object->p_key) is distinct from 'number' then raise exception 'Invalid integer field' using errcode='22023'; end if;
  v_value := (p_object->>p_key)::numeric;
  if v_value<>trunc(v_value) or v_value<p_min or v_value>p_max then raise exception 'Invalid integer range' using errcode='22023'; end if;
  return v_value::integer;
end $$;
create function app_private.json_uuid(p_object jsonb,p_key text,p_nullable boolean default true) returns uuid
language plpgsql immutable set search_path = '' as $$
begin
  if p_nullable and p_object->p_key = 'null'::jsonb then return null; end if;
  return app_private.import_text(p_object,p_key,36,true)::uuid;
end $$;

create function public.set_activity_preference(p_activity_id uuid,p_choice text,p_priority integer,p_note text) returns void
language plpgsql security definer set search_path = '' as $$
declare v_trip uuid; v_group uuid;
begin
  perform app_private.require_user();
  select a.trip_id,t.group_id into v_trip,v_group from public.activities a join public.trips t on t.id=a.trip_id where a.id=p_activity_id;
  perform app_private.lock_member(v_group,false);
  if p_choice is null then
    delete from public.activity_preferences where activity_id=p_activity_id and user_id=auth.uid();
    return;
  end if;
  if p_choice not in ('must','yes','maybe','skip') or p_priority is null or p_priority not between 0 and 5 or p_note is null or length(p_note)>1000 then raise exception 'Invalid preference' using errcode='22023'; end if;
  insert into public.activity_preferences(trip_id,activity_id,user_id,choice,priority,note)
  values(v_trip,p_activity_id,auth.uid(),p_choice,p_priority,p_note)
  on conflict(activity_id,user_id) do update set choice=excluded.choice,priority=excluded.priority,note=excluded.note,updated_at=now();
end $$;

create function public.create_activity_comment(p_activity_id uuid,p_body text,p_request_id uuid) returns uuid
language plpgsql security definer set search_path = '' as $$
declare v_trip uuid; v_group uuid; v_id uuid; v_args jsonb := jsonb_build_object('activity_id',p_activity_id,'body',p_body);
begin
  perform app_private.require_user();
  select a.trip_id,t.group_id into v_trip,v_group from public.activities a join public.trips t on t.id=a.trip_id where a.id=p_activity_id;
  perform app_private.lock_member(v_group,false);
  v_id := app_private.operation_result('create_activity_comment',p_request_id,v_args);
  if v_id is not null then return v_id; end if;
  insert into public.activity_comments(trip_id,activity_id,created_by,body) values(v_trip,p_activity_id,auth.uid(),btrim(p_body)) returning id into v_id;
  perform app_private.save_operation('create_activity_comment',p_request_id,v_args,v_id);
  return v_id;
end $$;
create function public.edit_activity_comment(p_comment_id uuid,p_body text,p_expected_version integer) returns void
language plpgsql security definer set search_path = '' as $$
declare v_group uuid; v_author uuid; v_version integer;
begin
  perform app_private.require_user();
  select t.group_id into v_group from public.activity_comments c join public.trips t on t.id=c.trip_id where c.id=p_comment_id;
  perform app_private.lock_member(v_group,false);
  select created_by,version into v_author,v_version from public.activity_comments where id=p_comment_id for update;
  if v_author is distinct from auth.uid() then raise exception 'Not authorized' using errcode='42501'; end if;
  if p_expected_version is null or v_version is distinct from p_expected_version then raise exception 'Comment changed; refresh before saving' using errcode='40001'; end if;
  update public.activity_comments set body=btrim(p_body),updated_at=now() where id=p_comment_id;
end $$;
create function public.delete_activity_comment(p_comment_id uuid,p_expected_version integer) returns void
language plpgsql security definer set search_path = '' as $$
declare v_group uuid; v_author uuid; v_version integer;
begin
  perform app_private.require_user();
  select t.group_id into v_group from public.activity_comments c join public.trips t on t.id=c.trip_id where c.id=p_comment_id;
  perform app_private.lock_member(v_group,false);
  select created_by,version into v_author,v_version from public.activity_comments where id=p_comment_id for update;
  if v_author is distinct from auth.uid() and not app_private.is_editor(v_group) then raise exception 'Not authorized' using errcode='42501'; end if;
  if p_expected_version is null or v_version is distinct from p_expected_version then raise exception 'Comment changed; refresh before deleting' using errcode='40001'; end if;
  delete from public.activity_comments where id=p_comment_id;
end $$;

create function public.save_itinerary_day(p_trip_id uuid,p_day_id uuid,p_fields jsonb,p_expected_version integer,p_request_id uuid) returns uuid
language plpgsql security definer set search_path = '' as $$
declare v_version integer; v_id uuid; v_old public.itinerary_days; v_fields jsonb; v_args jsonb; v_number integer; v_title text; v_notes text; v_stop uuid;
begin
  v_version := app_private.lock_plan(p_trip_id,true);
  perform app_private.allowed_keys(p_fields,array['day_number','title','stop_id','notes']);
  v_args := jsonb_build_object('trip_id',p_trip_id,'day_id',p_day_id,'fields',p_fields,'expected_version',p_expected_version);
  v_id := app_private.operation_result('save_itinerary_day',p_request_id,v_args);
  if v_id is not null then return v_id; end if;
  perform app_private.check_plan_version(v_version,p_expected_version);
  if p_day_id is null then
    v_fields := jsonb_build_object('title','','stop_id',null,'notes','') || p_fields;
  else
    select * into v_old from public.itinerary_days where id=p_day_id and trip_id=p_trip_id;
    if not found then raise exception 'Not authorized' using errcode='42501'; end if;
    v_fields := jsonb_build_object('day_number',v_old.day_number,'title',v_old.title,'stop_id',v_old.stop_id,'notes',v_old.notes) || p_fields;
  end if;
  v_number := app_private.json_integer(v_fields,'day_number',1,365);
  v_title := app_private.import_text(v_fields,'title',120);
  v_notes := app_private.import_text(v_fields,'notes',3000);
  v_stop := app_private.json_uuid(v_fields,'stop_id',true);
  if p_day_id is null then
    insert into public.itinerary_days(trip_id,day_number,title,stop_id,notes) values(p_trip_id,v_number,v_title,v_stop,v_notes) returning id into v_id;
  else
    update public.itinerary_days set day_number=v_number,title=v_title,stop_id=v_stop,notes=v_notes where id=p_day_id returning id into v_id;
  end if;
  perform app_private.save_operation('save_itinerary_day',p_request_id,v_args,v_id);
  return v_id;
end $$;
create function public.delete_itinerary_day(p_day_id uuid,p_expected_version integer) returns void
language plpgsql security definer set search_path = '' as $$
declare v_trip uuid; v_version integer;
begin
  select trip_id into v_trip from public.itinerary_days where id=p_day_id;
  v_version := app_private.lock_plan(v_trip,true);
  perform app_private.check_plan_version(v_version,p_expected_version);
  if exists(select 1 from public.itinerary_items where day_id=p_day_id) then raise exception 'Move or remove day items before deleting this day' using errcode='23503'; end if;
  delete from public.itinerary_days where id=p_day_id;
end $$;
create function public.save_itinerary_item(p_trip_id uuid,p_item_id uuid,p_fields jsonb,p_expected_version integer,p_request_id uuid) returns uuid
language plpgsql security definer set search_path = '' as $$
declare
  v_version integer; v_id uuid; v_old public.itinerary_items; v_fields jsonb; v_args jsonb;
  v_day uuid; v_activity uuid; v_title text; v_position integer; v_time text; v_duration integer; v_notes text; v_alt boolean; v_subgroup text;
begin
  v_version := app_private.lock_plan(p_trip_id,true);
  perform app_private.allowed_keys(p_fields,array['day_id','activity_id','title','position','time_slot','duration_minutes','notes','is_alternative','subgroup']);
  v_args := jsonb_build_object('trip_id',p_trip_id,'item_id',p_item_id,'fields',p_fields,'expected_version',p_expected_version);
  v_id := app_private.operation_result('save_itinerary_item',p_request_id,v_args);
  if v_id is not null then return v_id; end if;
  perform app_private.check_plan_version(v_version,p_expected_version);
  if p_item_id is null then
    v_fields := jsonb_build_object('activity_id',null,'position',0,'time_slot',null,'duration_minutes',null,'notes','','is_alternative',false,'subgroup','') || p_fields;
  else
    select * into v_old from public.itinerary_items where id=p_item_id and trip_id=p_trip_id;
    if not found then raise exception 'Not authorized' using errcode='42501'; end if;
    v_fields := jsonb_build_object('day_id',v_old.day_id,'activity_id',v_old.activity_id,'title',v_old.title,'position',v_old.position,'time_slot',v_old.time_slot,'duration_minutes',v_old.duration_minutes,'notes',v_old.notes,'is_alternative',v_old.is_alternative,'subgroup',v_old.subgroup) || p_fields;
  end if;
  v_day := app_private.json_uuid(v_fields,'day_id',false);
  v_activity := app_private.json_uuid(v_fields,'activity_id',true);
  v_title := app_private.import_text(v_fields,'title',200,true);
  v_position := app_private.json_integer(v_fields,'position',0,10000);
  if v_fields->'time_slot'='null'::jsonb then v_time:=null; else v_time:=app_private.import_text(v_fields,'time_slot',5); end if;
  if v_time is not null and v_time !~ '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$' then raise exception 'Invalid time slot' using errcode='22023'; end if;
  v_duration := app_private.json_integer(v_fields,'duration_minutes',0,1440,true);
  v_notes := app_private.import_text(v_fields,'notes',3000);
  if jsonb_typeof(v_fields->'is_alternative') is distinct from 'boolean' then raise exception 'Invalid alternative flag' using errcode='22023'; end if;
  v_alt := (v_fields->>'is_alternative')::boolean;
  v_subgroup := app_private.import_text(v_fields,'subgroup',120);
  if p_item_id is null then
    insert into public.itinerary_items(trip_id,day_id,activity_id,title,position,time_slot,duration_minutes,notes,is_alternative,subgroup)
    values(p_trip_id,v_day,v_activity,btrim(v_title),v_position,v_time,v_duration,v_notes,v_alt,v_subgroup) returning id into v_id;
  else
    update public.itinerary_items set day_id=v_day,activity_id=v_activity,title=btrim(v_title),position=v_position,time_slot=v_time,duration_minutes=v_duration,notes=v_notes,is_alternative=v_alt,subgroup=v_subgroup where id=p_item_id returning id into v_id;
  end if;
  perform app_private.save_operation('save_itinerary_item',p_request_id,v_args,v_id);
  return v_id;
end $$;
create function public.delete_itinerary_item(p_item_id uuid,p_expected_version integer) returns void
language plpgsql security definer set search_path = '' as $$
declare v_trip uuid; v_version integer;
begin
  select trip_id into v_trip from public.itinerary_items where id=p_item_id;
  v_version := app_private.lock_plan(v_trip,true);
  perform app_private.check_plan_version(v_version,p_expected_version);
  delete from public.itinerary_items where id=p_item_id;
end $$;
create function public.set_trip_start_date(p_trip_id uuid,p_start_date date,p_expected_version integer) returns void
language plpgsql security definer set search_path = '' as $$
declare v_version integer;
begin
  v_version := app_private.lock_plan(p_trip_id,true);
  perform app_private.check_plan_version(v_version,p_expected_version);
  -- Dates label relative days only; stored anchors/booking metadata are unchanged.
  update public.trips set start_date=p_start_date where id=p_trip_id and start_date is distinct from p_start_date;
end $$;
create function public.set_plan_approval(p_trip_id uuid,p_expected_version integer,p_approved boolean) returns void
language plpgsql security definer set search_path = '' as $$
declare v_version integer;
begin
  v_version := app_private.lock_plan(p_trip_id,false);
  perform app_private.check_plan_version(v_version,p_expected_version);
  if p_approved is null then raise exception 'Approval value required' using errcode='22023'; end if;
  if not p_approved then
    delete from public.plan_approvals where trip_id=p_trip_id and user_id=auth.uid();
    return;
  end if;
  if not exists(select 1 from public.trip_participants where trip_id=p_trip_id and user_id=auth.uid() and status='going') then raise exception 'Only going participants can approve' using errcode='42501'; end if;
  insert into public.plan_approvals(trip_id,user_id,version) values(p_trip_id,auth.uid(),v_version)
  on conflict(trip_id,user_id) do update set version=excluded.version,approved_at=now();
end $$;
create function public.set_member_display_name(p_group_id uuid,p_display_name text) returns void
language plpgsql security definer set search_path = '' as $$
begin
  perform app_private.lock_member(p_group_id,false);
  if p_display_name is null or length(p_display_name)>80 then raise exception 'Invalid display name' using errcode='22023'; end if;
  update public.group_members set display_name=btrim(p_display_name) where group_id=p_group_id and user_id=auth.uid();
end $$;

-- One statement gives the displayed content, members and approval version the
-- same MVCC snapshot. Caller privileges and RLS apply to every subquery.
create function public.get_plan_snapshot(p_trip_id uuid) returns jsonb
language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object(
    'trip',to_jsonb(t),
    'activities',coalesce((select jsonb_agg(to_jsonb(a) order by a.created_at,a.id) from public.activities a where a.trip_id=t.id),'[]'::jsonb),
    'stops',coalesce((select jsonb_agg(to_jsonb(s) order by s.position,s.id) from public.trip_stops s where s.trip_id=t.id),'[]'::jsonb),
    'days',coalesce((select jsonb_agg(to_jsonb(d) order by d.day_number,d.id) from public.itinerary_days d where d.trip_id=t.id),'[]'::jsonb),
    'items',coalesce((select jsonb_agg(to_jsonb(i) order by d.day_number,i.position,i.id) from public.itinerary_items i join public.itinerary_days d on d.id=i.day_id and d.trip_id=i.trip_id where i.trip_id=t.id),'[]'::jsonb),
    'approvals',coalesce((select jsonb_agg(to_jsonb(a) order by a.user_id) from public.plan_approvals a where a.trip_id=t.id),'[]'::jsonb),
    'members',coalesce((select jsonb_agg(to_jsonb(m) order by m.joined_at,m.user_id) from public.group_members m where m.group_id=t.group_id),'[]'::jsonb),
    'participants',coalesce((select jsonb_agg(to_jsonb(p) order by p.user_id) from public.trip_participants p where p.trip_id=t.id),'[]'::jsonb)
  ) from public.trips t where t.id=p_trip_id
$$;

create function public.get_activity_collaboration(p_activity_id uuid) returns jsonb
language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object(
    'preferences',coalesce((select jsonb_agg(to_jsonb(p) order by p.user_id) from public.activity_preferences p where p.activity_id=a.id),'[]'::jsonb),
    'comments',coalesce((select jsonb_agg(to_jsonb(c) order by c.created_at,c.id) from public.activity_comments c where c.activity_id=a.id),'[]'::jsonb),
    'members',coalesce((select jsonb_agg(to_jsonb(m) order by m.joined_at,m.user_id) from public.group_members m where m.group_id=t.group_id),'[]'::jsonb),
    'participants',coalesce((select jsonb_agg(to_jsonb(p) order by p.user_id) from public.trip_participants p where p.trip_id=t.id),'[]'::jsonb)
  ) from public.activities a join public.trips t on t.id=a.trip_id where a.id=p_activity_id
$$;
create function public.get_preference_snapshot(p_trip_id uuid) returns jsonb
language sql stable security invoker set search_path = '' as $$
  select jsonb_build_object(
    'preferences',coalesce((select jsonb_agg(to_jsonb(p) order by p.activity_id,p.user_id) from public.activity_preferences p where p.trip_id=t.id),'[]'::jsonb),
    'members',coalesce((select jsonb_agg(to_jsonb(m) order by m.joined_at,m.user_id) from public.group_members m where m.group_id=t.group_id),'[]'::jsonb),
    'participants',coalesce((select jsonb_agg(to_jsonb(p) order by p.user_id) from public.trip_participants p where p.trip_id=t.id),'[]'::jsonb)
  ) from public.trips t where t.id=p_trip_id
$$;

revoke all on function app_private.clear_removed_member_choices(), app_private.lock_plan(uuid,boolean), app_private.check_plan_version(integer,integer), app_private.json_integer(jsonb,text,integer,integer,boolean), app_private.json_uuid(jsonb,text,boolean) from public,anon,authenticated;
revoke all on function public.set_activity_preference(uuid,text,integer,text), public.create_activity_comment(uuid,text,uuid), public.edit_activity_comment(uuid,text,integer), public.delete_activity_comment(uuid,integer), public.save_itinerary_day(uuid,uuid,jsonb,integer,uuid), public.delete_itinerary_day(uuid,integer), public.save_itinerary_item(uuid,uuid,jsonb,integer,uuid), public.delete_itinerary_item(uuid,integer), public.set_trip_start_date(uuid,date,integer), public.set_plan_approval(uuid,integer,boolean), public.set_member_display_name(uuid,text) from public,anon,authenticated;
grant execute on function public.set_activity_preference(uuid,text,integer,text), public.create_activity_comment(uuid,text,uuid), public.edit_activity_comment(uuid,text,integer), public.delete_activity_comment(uuid,integer), public.save_itinerary_day(uuid,uuid,jsonb,integer,uuid), public.delete_itinerary_day(uuid,integer), public.save_itinerary_item(uuid,uuid,jsonb,integer,uuid), public.delete_itinerary_item(uuid,integer), public.set_trip_start_date(uuid,date,integer), public.set_plan_approval(uuid,integer,boolean), public.set_member_display_name(uuid,text) to authenticated;
revoke all on function public.get_plan_snapshot(uuid), public.get_activity_collaboration(uuid), public.get_preference_snapshot(uuid) from public,anon,authenticated;
grant execute on function public.get_plan_snapshot(uuid), public.get_activity_collaboration(uuid), public.get_preference_snapshot(uuid) to authenticated;

-- Source: 202610040003_profiles_group_names.sql
-- Upgrade an existing installation AFTER migrations 001 and 002.
-- No trips, activities, preferences, invitations or existing names are deleted.
-- Existing group names remain aliases until a member explicitly clears them.

do $$
begin
  if to_regprocedure('public.set_member_display_name(uuid,text)') is null then
    raise exception 'Install migrations 001 and 002 before this upgrade. No changes applied.';
  end if;
  if to_regclass('public.profiles') is not null then
    raise exception 'Profiles already exist. Check migration history before rerunning. No changes applied.';
  end if;
end $$;

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (length(btrim(display_name)) between 1 and 80),
  version integer not null default 1 check (version > 0),
  updated_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
create policy profiles_read_self on public.profiles for select to authenticated
  using (user_id = (select auth.uid()));
revoke all on public.profiles from public, anon, authenticated;
grant select on public.profiles to authenticated;

-- Replace the old name-column grant: all renames must use version-checked RPC.
revoke update(name) on public.groups from public,anon,authenticated;
revoke update on public.groups from public,anon,authenticated;
alter table public.groups add column version integer not null default 1 check (version > 0);
alter table public.group_members add column nickname text check (length(nickname) between 1 and 80);
-- Preserve previously chosen group-specific names, rather than silently overwriting them.
update public.group_members set nickname = nullif(btrim(display_name), '');

-- display_name remains a membership-scoped projection. Other users never read profiles.
-- Use the same per-user lock for profile updates and new memberships to avoid stale copies.
create function app_private.project_member_name() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('profile:' || new.user_id::text, 0));
  new.display_name := coalesce(new.nickname,
    (select p.display_name from public.profiles p where p.user_id = new.user_id), '');
  return new;
end $$;
create trigger member_name_projection before insert or update of nickname,display_name
  on public.group_members for each row execute function app_private.project_member_name();
revoke all on function app_private.project_member_name() from public,anon,authenticated;

create function public.get_my_profile() returns jsonb
language plpgsql security invoker set search_path = '' as $$
declare v_result jsonb;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  select jsonb_build_object('display_name',p.display_name,'version',p.version)
    into v_result from public.profiles p where p.user_id = auth.uid();
  return coalesce(v_result, jsonb_build_object('display_name','','version',0));
end $$;

create function public.update_my_profile(p_display_name text,p_expected_version integer) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_user uuid; v_version integer;
begin
  v_user := app_private.require_user();
  if p_display_name is null or length(btrim(p_display_name)) not between 1 and 80
     or p_display_name ~ '[[:cntrl:]]' then
    raise exception 'Invalid display name (1-80 characters required)' using errcode='22023';
  end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('profile:' || v_user::text,0));
  select version into v_version from public.profiles where user_id=v_user for update;
  if p_expected_version is null or p_expected_version is distinct from coalesce(v_version,0) then
    raise exception 'Profile changed; refresh before saving' using errcode='40001';
  end if;
  insert into public.profiles(user_id,display_name) values(v_user,btrim(p_display_name))
    on conflict(user_id) do update set display_name=excluded.display_name,
      version=public.profiles.version+1,updated_at=now();
  update public.group_members set display_name=btrim(p_display_name)
    where user_id=v_user and nickname is null;
  return public.get_my_profile();
end $$;

-- Empty nickname means "use my account name"; only the caller's own membership is writable.
create or replace function public.set_member_display_name(p_group_id uuid,p_display_name text) returns void
language plpgsql security definer set search_path = '' as $$
begin
  perform app_private.require_user();
  if p_display_name is null or length(btrim(p_display_name))>80 or p_display_name ~ '[[:cntrl:]]' then
    raise exception 'Invalid display name' using errcode='22023';
  end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('profile:' || auth.uid()::text,0));
  perform app_private.lock_member(p_group_id,false);
  update public.group_members set nickname=nullif(btrim(p_display_name),'')
    where group_id=p_group_id and user_id=auth.uid();
end $$;

create function public.rename_group(p_group_id uuid,p_name text,p_expected_version integer) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_version integer; v_result jsonb;
begin
  perform app_private.lock_member(p_group_id,true);
  if p_name is null or length(btrim(p_name)) not between 1 and 120 or p_name ~ '[[:cntrl:]]' then
    raise exception 'Invalid group name' using errcode='22023';
  end if;
  select version into v_version from public.groups where id=p_group_id for update;
  if p_expected_version is null or v_version is distinct from p_expected_version then
    raise exception 'Group changed; refresh before saving' using errcode='40001';
  end if;
  update public.groups set name=btrim(p_name),version=version+1 where id=p_group_id
    returning jsonb_build_object('id',id,'name',name,'created_by',created_by,'version',version) into v_result;
  return v_result;
end $$;

revoke all on function public.get_my_profile(), public.update_my_profile(text,integer),
  public.set_member_display_name(uuid,text), public.rename_group(uuid,text,integer) from public,anon,authenticated;
grant execute on function public.get_my_profile(), public.update_my_profile(text,integer),
  public.set_member_display_name(uuid,text), public.rename_group(uuid,text,integer) to authenticated;
-- Existing group SELECT includes version and nickname; no direct mutation grants are added.
notify pgrst, 'reload schema';

commit;
